version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80